import type { Metadata } from "next";
import { Kanit,K2D } from "next/font/google";
import "../globals.css";

const kanit = Kanit({
  weight: ["200", "300", "400", "500", "600"],
  subsets: ["thai"],
});

const k2d = K2D({
  weight: ["200", "300", "400", "500", "600"],
  subsets: ["thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WebsiteRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <h1 className={k2d.className}>Header</h1>
        <hr />
        {children}
      </body>
    </html>
  );
}
